DELETE FROM VEHICLE
WHERE DEPOT_ID = 'D001'
AND VEHICLE_ID = 'V101';


DELETE FROM MECHANIC
WHERE DEPOT_ID = 'D001'
AND MECHANIC_ID = 'M001';


DELETE FROM SPARE_PARTS
WHERE PART_ID = 'P001';


DELETE FROM MAINTENANCE_LOG
WHERE LOG_ID = 'L001';