INSERT INTO DEPOT (DEPOT_ID, PART_NAME)
VALUES ('D001', 'Brake Pad');


INSERT INTO VEHICLE
(DEPOT_ID, VEHICLE_ID, MODEL, OPERATIONAL_STATUS, VEHICLE_TYPE, FUEL_TYPE)
VALUES
('D001', 'V101', 'Mercedes Bus', 'Active', 'Bus', 'Diesel');


INSERT INTO MECHANIC
(DEPOT_ID, MECHANIC_ID, PART_NAME)
VALUES
('D001', 'M001', 'Engine');


INSERT INTO SPARE_PARTS
(PART_ID, COST, PART_NAME, CATEGORY)
VALUES
('P001', 1500, 'Brake Pad', 'Mechanical');