SELECT
    M.MECHANIC_ID,
    V.VEHICLE_ID,
    V.MODEL
FROM MECHANIC M
JOIN WORKS_ON W
ON M.DEPOT_ID = W.MEC_DEPOT_ID
AND M.MECHANIC_ID = W.MECHANIC_ID
JOIN VEHICLE V
ON V.DEPOT_ID = W.DEPOT_ID
AND V.VEHICLE_ID = W.VEHICLE_ID;


SELECT
    ML.LOG_ID,
    V.MODEL,
    ML.DATE
FROM MAINTENANCE_LOG ML
JOIN VEHICLE V
ON ML.DEPOT_ID = V.DEPOT_ID
AND ML.VEHICLE_ID = V.VEHICLE_ID;

SELECT
    M.MECHANIC_ID,
    S.PART_NAME,
    S.CATEGORY
FROM PART_USAGE PU
JOIN MECHANIC M
ON PU.DEPOT_ID = M.DEPOT_ID
AND PU.MECHANIC_ID = M.MECHANIC_ID
JOIN SPARE_PARTS S
ON PU.PART_ID = S.PART_ID;


SELECT
    D.DEPOT_ID,
    V.VEHICLE_ID,
    V.MODEL
FROM DEPOT D
JOIN VEHICLE V
ON D.DEPOT_ID = V.DEPOT_ID;