UPDATE VEHICLE
SET OPERATIONAL_STATUS = 'Under Maintenance'
WHERE DEPOT_ID = 'D001'
AND VEHICLE_ID = 'V101';


UPDATE VEHICLE
SET FUEL_TYPE = 'Electric'
WHERE DEPOT_ID = 'D001'
AND VEHICLE_ID = 'V101';


UPDATE SPARE_PARTS
SET COST = 2000
WHERE PART_ID = 'P001';


UPDATE MAINTENANCE_DEPOT
SET CREW = 'Night Shift Team'
WHERE DEPOT_ID = 'D001';